name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '13.x'
      - name: Update README.md file
        run: node index.js
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: A-chelbi
          force: false
          signoff: false
          message: ':memo: README.md updated by Gabot'
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
